version: '3'

services:
  nodeapp:
   image: vtdthang/nodeapp:1.0
   ports:
     - 3033:3033
   deploy:
     replicas: 15
     restart_policy:
       max_attempts: 3
       condition: on-failure
     update_config:
       parallelism: 3
       delay: 10s
   networks: 
    - balance 
  
  proxy:
    image: vtdthang/swarm_balancer:1.0
    ports:
      - 80:80
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay